version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:                                                                                                                                                   
      - mongo
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db 
      - /home/vipinrr/Pictures/Brototype/E-commerce-Mini-Project/E-commerce/productImages:/data/productImages  
volumes:
  mongo_data:
